source/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/login(.:format)', to: 'sessions#create'

  devise_scope :user do
    authenticated :user do
      root 'lists#index', as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :lists do
    resources :tasks
  end

  get "/sync", to: "application#sync"
  get "/auth/:provider/callback" => "sessions#create"

end

source/app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true

  REQUIRED_LIST_PARAMS = [:name, :updated_at, :identifier]

  include WithIdentifier

  def to_s
    name
  end

  class << self

    def valid_list(list_params)
      (REQUIRED_LIST_PARAMS - list_params.keys).empty?
    end

    def update_list list, list_params
      if list.updated_at < list_params[:updated_at]
        list.update_attributes(list_params.slice(*REQUIRED_LIST_PARAMS))
      end
    end


    def sync user, lists
      lists.each do |list_params|
        list_params.stringify_keys!

        tasks = list_params.delete("tasks")

        if valid_list(list_params)
          if (list = user.lists.find_by(identifier: list_params[:identifier])).present?

          update_list(list, list_params)

          else
            user.create_list(list_params.slice(*REQUIRED_LIST_PARAMS))
          end
        end

        Task.sync(list, tasks) if tasks
      end
    end
  end
end

source/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :edit
  load_and_authorize_resource :list

  def index
    @lists = @lists.where(user_id: current_user.id)
    lists_count = @lists.count
    @lists = @lists.page(current_page).per(per_page)
    respond_to do |format|
      format.html
      format.json { render json: { lists_count: lists_count, lists: @lists } }
    end
  end

  def show
    @q1_tasks = @list.tasks.quarter1
    @q2_tasks = @list.tasks.quarter2
    @q3_tasks = @list.tasks.quarter3
    @q4_tasks = @list.tasks.quarter4
    respond_to do |format|
      format.html
      format.json { render json: @list }
    end
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = current_user.lists.create(list_params)

    respond_with @list, serializer: ListSerializer
  end

  def update
    @list.update_attributes(list_params)

    respond_with @list, serializer: ListSerializer
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

source/app/views/lists/_form.slim
.default-form
  = simple_form_for(@list) do |f|
    = f.error_notification

    .form-group
      label Nazwa
      = f.input :name, label: false, input_html: { class: 'form-control' }

    .form-actions
      = f.button :submit, class: 'btn btn-primary', value: 'Dodaj listę'

source/app/views/lists/_list_links.slim
.row
  .col-lg-12.breadcrumbs
    .pull-left
      = link_to "Wróć", lists_path, class: 'btn btn-default'
      - unless @list.new_record?
        = link_to 'Dodaj zadanie', new_list_task_path(@list), class: 'btn btn-success'
    .pull-right
      - if @list.new_record?
        = link_to 'Anuluj', lists_path, class: 'btn btn-danger'
      - else
        = link_to "Edytuj", edit_list_path(@list), class: 'btn btn-info'
        = link_to "Usuń", list_path(@list), class: 'btn btn-danger', data: {confirm: "Na pewno usunąć listę wraz z wszystkimi zadaniami?"}, method: :delete

source/app/views/lists/_matrix.slim
.row
  .col-sm-1
  .col-sm-11
    .row
      .col-lg-6
        h3.center Pilne
      .col-lg-6
        h3.center Niepilne
.row
  .col-sm-1
    .row.axis-description
      .col-lg-12
        .matrix-quarter
          h3.vertical-text Ważne
    .row.axis-description
      .col-lg-12
        .matrix-quarter
          h3.vertical-text Nieważne

  .col-sm-11
    .col-lg-12.matrix-wrapper
      .row
        #quarter-1.col-lg-6.matrix-quarter
          - @q1_tasks.each do |task|
            .task-wrapper style="top:#{task.y}px;left:#{task.x}px;"
                span class="label label-#{Task.random_label}"
                  = task.name
                  = link_to edit_list_task_path(@list, task) do
                    i.icon.icon-pencil
                  = link_to list_task_path(@list, task), data: { confirm: "Na pewno chcesz usunąć to zadanie?"}, method: :delete do
                    i.icon.icon-trash

        #quarter-2.col-lg-6.matrix-quarter
          - @q2_tasks.each do |task|
            .task-wrapper style="top:#{task.y}px;left:#{task.x}px;"
                span class="label label-#{Task.random_label}"
                  = task.name
                  = link_to edit_list_task_path(@list, task) do
                    i.icon.icon-pencil
                  = link_to list_task_path(@list, task), data: { confirm: "Na pewno chcesz usunąć to zadanie?"}, method: :delete do
                    i.icon.icon-trash

      .row
        #quarter-3.col-lg-6.matrix-quarter
          - @q3_tasks.each do |task|
            .task-wrapper style="top:#{task.y}px;left:#{task.x}px;"
                span class="label label-#{Task.random_label}"
                  = task.name
                  = link_to edit_list_task_path(@list, task) do
                    i.icon.icon-pencil
                  = link_to list_task_path(@list, task), data: { confirm: "Na pewno chcesz usunąć to zadanie?"}, method: :delete do
                    i.icon.icon-trash

        #quarter-4.col-lg-6.matrix-quarter
          - @q4_tasks.each do |task|
            .task-wrapper style="top:#{task.y}px;left:#{task.x}px;"
                span class="label label-#{Task.random_label}"
                  = task.name
                  = link_to edit_list_task_path(@list, task) do
                    i.icon.icon-pencil
                  = link_to list_task_path(@list, task), data: { confirm: "Na pewno chcesz usunąć to zadanie?"}, method: :delete do
                    i.icon.icon-trash

source/app/views/lists/edit.slim
= render 'list_links'

h3.title = "Edytuj listę #{@list.name}"

= render 'form'

source/app/views/lists/index.slim
.list-group
  - @lists.each do |list|
    = link_to list, class: 'list-group-item'
      span.badge
        = list.tasks.count
      = list.name


= link_to "Dodaj listę zadań", new_list_path, class: 'btn btn-primary'


nav.pagination-wrapper
  ul.pagination
    = paginate @lists, window: 2

source/app/views/lists/new.slim
= render 'list_links'

h3.title Dodaj Listę

= render 'form'

source/app/views/lists/show.slim
= render 'list_links'

.row
  .col-lg-12
    h3 = @list.name

= render 'matrix'