source/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/login(.:format)', to: 'sessions#create'

  devise_scope :user do
    authenticated :user do
      root 'lists#index', as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :lists do
    resources :tasks
  end

  get "/sync", to: "application#sync"
  get "/auth/:provider/callback" => "sessions#create"

end

source/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  include WithIdentifier

  REQUIRED_TASK_PARAMS = [:name, :updated_at, :identifier]
  OPTIONAL_TASK_PARAMS = [:x, :y, :duration, :priority]
  ALL_TASK_PARAMS = REQUIRED_TASK_PARAMS | OPTIONAL_TASK_PARAMS

  PRIORITIES = (1..4).to_a
  QUARTER_SIZE = { x: 500, y: 500 }

  QUARTER_1 = {
                x: { min: 1, max: QUARTER_SIZE[:x] },
                y: { min: 1, max: QUARTER_SIZE[:y] }
              }
  QUARTER_2 = {
                x: { min: QUARTER_SIZE[:x]+1, max: 2*QUARTER_SIZE[:x] },
                y: { min: 1, max: QUARTER_SIZE[:y] }
              }
  QUARTER_3 = {
                x: { min: 1, max: QUARTER_SIZE[:x] },
                y: { min: QUARTER_SIZE[:x]+1, max: 2*QUARTER_SIZE[:y] }
              }
  QUARTER_4 = {
                x: { min: QUARTER_SIZE[:x]+1, max: 2*QUARTER_SIZE[:x] },
                y: { min: QUARTER_SIZE[:y]+1, max: 2*QUARTER_SIZE[:y] }
              }

  scope :quarter1, ->{ where(priority: 1) }
  scope :quarter2, ->{ where(priority: 2) }
  scope :quarter3, ->{ where(priority: 3) }
  scope :quarter4, ->{ where(priority: 4) }


  after_initialize :set_position
  AVAILABLE_LABELS = ["Default", "Primary", "Success", "Info", "Warning", "Danger"]

  def self.random_label
    AVAILABLE_LABELS[rand(AVAILABLE_LABELS.length)].downcase
  end

  private

  def set_position
    self.duration ||= rand(4)+1
    self.priority ||= rand(PRIORITIES.length)+1
    self.x ||= rand(QUARTER_SIZE[:x])
    self.y ||= rand(QUARTER_SIZE[:y])
  end

  class << self

    def valid_task(task_params)
      (REQUIRED_TASK_PARAMS - task_params.keys).empty?
    end

    def update_task task, task_params
      if task.updated_at < task_params[:updated_at]
        task.update_attributes(task_params.slice(*ALL_TASK_PARAMS))
      end
    end


    def sync list, tasks
      tasks.each do |task_params|
        task_params.stringify_keys!

        if valid_task(task_params)
          if (task = list.tasks.find_by(identifier: task_params[:identifier])).present?

          update_task(task, task_params)

          else
            list.create_list(task_params.slice(*REQUIRED_TASK_PARAMS))
          end
        end
      end
    end
  end
end

source/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_resource :list
  load_and_authorize_resource :task, through: :list

  respond_to :html

  def index
    @tasks = @list.tasks.all

    respond_to do |format|
      format.html
      format.json { render json: { tasks_count: @list.tasks.count, tasks: @tasks } }
    end
  end

  def show
    respond_with(@task)
  end

  def new
    @task = @list.tasks.new
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = @list.tasks.new(task_params)
    @task.save
    respond_with(@task, location: @list)
  end

  def update
    @task.update(task_params)
    respond_with(@task, location: @list)
  end

  def destroy
    @task.destroy
    respond_with(@list)
  end

  private

  def task_params
    params.require(:task).permit(:name, :list_id, :duration, :priority, :x, :y)
  end
end

source/app/helpers/tasks_helper.rb
module TasksHelper
end

source/app/views/tasks/_form.html.slim
.default-form
  = simple_form_for([@list, @task]) do |f|
    = f.error_notification

    .form-group
      label Nazwa
      = f.input :name, input_html: { class: 'form-control'}, label: false

    .form-group
      label Ilość Cykli
      = f.input :duration, input_html: { class: 'form-control'}, label: false


    .row
      .col-lg-4
        .input-group
          label Priorytet
          = f.input :priority, as: :select, collection: Task::PRIORITIES, include_blank: false, input_html: { class: 'form-control'}, label: false
      .col-lg-4
        .input-group
          label Pozycja X
          = f.input :x, input_html: { class: 'form-control'}, label: false
      .col-lg-4
        .input-group
          label Pozycja Y
          = f.input :y, input_html: { class: 'form-control'}, label: false

    .form-actions
      = f.button :submit, class: 'btn btn-primary', value: "Dodaj zadanie"

source/app/views/tasks/_task_links.slim
.row
  .col-lg-12.breadcrumbs
    .pull-left
      = link_to "Wróć", @list, class: 'btn btn-default'
      = link_to 'Dodaj zadanie', new_list_task_path(@list), class: 'btn btn-success'
    .pull-right
      - if @task.new_record?
        = link_to 'Anuluj', lists_path, class: 'btn btn-danger'
      - else
        = link_to "Edytuj", edit_list_task_path(@list, @task), class: 'btn btn-info'
        = link_to 'Usuń', list_task_path(@list, @task), class: 'btn btn-danger', data: {confirm: 'Na pewno usunąć to zadanie?'}, method: :delete

source/app/views/tasks/edit.html.slim
= render 'task_links'

h1 Edytuj zadanie

= render 'form'

source/app/views/tasks/index.html.slim
= render 'lists/list_links'

.row
  .col-lg-12
    h3 = @list.name

= render 'lists/matrix'

source/app/views/tasks/new.html.slim
= render 'task_links'

h1 Nowe zadanie

= render 'form'

source/app/views/tasks/show.html.slim
p#notice = notice

p
  strong Name:
  = @task.name
p
  strong List:
  = @task.list
p
  strong Duration:
  = @task.duration
p
  strong Priority:
  = @task.priority

= link_to 'Edit', edit_task_path(@task)
'|
= link_to 'Back', tasks_path